-- MySQL Script generated by MySQL Workbench
-- Fri Feb 19 17:46:03 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mycampus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mycampus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mycampus` DEFAULT CHARACTER SET utf8 ;
USE `mycampus` ;

-- -----------------------------------------------------
-- Table `mycampus`.`Semesters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Semesters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` YEAR NOT NULL,
  `term` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `semester_id` INT NOT NULL,
  `subject` CHAR(4) NOT NULL,
  `code` CHAR(5) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Courses_Semesters1_idx` (`semester_id` ASC),
  CONSTRAINT `fk_Courses_Semesters1`
    FOREIGN KEY (`semester_id`)
    REFERENCES `mycampus`.`Semesters` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Course_Levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Course_Levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `level_id` INT NOT NULL,
  INDEX `fk_Course_Levels_Courses_idx` (`course_id` ASC),
  INDEX `fk_Course_Levels_Levels_idx` (`level_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Course_Levels_Courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `mycampus`.`Courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Course_Levels_Levels`
    FOREIGN KEY (`level_id`)
    REFERENCES `mycampus`.`Levels` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Sections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Sections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `section` CHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sections_Type_idx` (`type_id` ASC),
  INDEX `fk_Sections_Courses_idx` (`course_id` ASC),
  CONSTRAINT `fk_Sections_Type`
    FOREIGN KEY (`type_id`)
    REFERENCES `mycampus`.`Types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sections_Courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `mycampus`.`Courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Section_Availability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Section_Availability` (
  `section_id` INT NOT NULL,
  `capacity` INT NOT NULL,
  `actual` INT NOT NULL,
  `remaining` INT NOT NULL,
  PRIMARY KEY (`section_id`),
  INDEX `fk_Section_Availability_Sections_idx` (`section_id` ASC),
  CONSTRAINT `fk_Section_Availability_Sections`
    FOREIGN KEY (`section_id`)
    REFERENCES `mycampus`.`Sections` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Section_Instructors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Section_Instructors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section_id` INT NOT NULL,
  `instructor_id` INT NOT NULL,
  `primary_instructor` TINYINT(1) NOT NULL,
  INDEX `fk_Section_Instructors_Sections_idx` (`section_id` ASC),
  INDEX `fk_Section_Instructors_Instructors_idx` (`instructor_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Section_Instructors_Sections`
    FOREIGN KEY (`section_id`)
    REFERENCES `mycampus`.`Sections` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Section_Instructors_Instructors`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `mycampus`.`Instructors` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `section_id` INT NOT NULL,
  `week` INT NOT NULL DEFAULT 0,
  `day` CHAR(1) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sessions_Sections_idx` (`section_id` ASC),
  CONSTRAINT `fk_Sessions_Sections`
    FOREIGN KEY (`section_id`)
    REFERENCES `mycampus`.`Sections` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mycampus`.`Session_Period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mycampus`.`Session_Period` (
  `session_id` INT NOT NULL,
  `start_date` DATE NULL,
  `finish_date` DATE NULL,
  `start_time` TIME NULL,
  `finish_time` TIME NULL,
  PRIMARY KEY (`session_id`),
  INDEX `fk_Session_Period_Sessions_idx` (`session_id` ASC),
  CONSTRAINT `fk_Session_Period_Sessions`
    FOREIGN KEY (`session_id`)
    REFERENCES `mycampus`.`Sessions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
